version: "3"
services:
    gcc:
        env_file: .env
        container_name: ${container_name_gcloud}
        build: .
        image: ${image_name_gcloud}
        volumes:
            - ./share:${container_mount_volume}
        stdin_open: true
        tty: true 
